---
apiVersion: v1
data:
  console: "true"
  console-authentication: internal
  console-password: "barney"
  console-user: "rubble"
  ingress: loadbalancer
  name: skupper-north
  router-console: "false"
  router-logging: ""
  router-mode: interior
  service-controller: "true"
  service-sync: "true"
kind: ConfigMap
metadata:
  name: skupper-site
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongo-a
  labels:
    application: mongo-a
  annotations:
    skupper.io/proxy: tcp
    skupper.io/address: mongo-a
    skupper.io/port: 27017:27017
spec:
  replicas: 1
  selector:
    matchLabels:
      application: mongo-a
  template:
    metadata:
      labels:
        application: mongo-a
    spec:
      containers: 
        - image: mongo:5.0
          name: mongo-a
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - "*"
          imagePullPolicy: Always
          volumeMounts: 
            - mountPath: /data/db
              name: mongodb-data
      volumes: 
        - name: mongodb-data
          emptyDir: {}
---
